### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by CristhianMotoche** [PythonForum/join_PythonForum#1]
Hello, I'm Cristhian, and I'm from Ecuador. I'd like to be part of your Forum, because I enjoy programming in python, and I'd like to share my ideas and code with you. But I want to know what kind of license are you going to use for your repositories. I love Free Software (Software Libre) and I'd like to support it.

**Comment by micseydel** [comment]
Hey Cristhian,

You can join us on python-forum.org, but this group hasn't been used in quite a while. For whatever reason the interest petered out.

As far as licenses, we're all for open source and free software though we didn't discuss it. I imagine we'd use MIT or perhaps GPL. I'm personally partial toward MIT. Since it hasn't been decided, if you were part of anything that got put together you'd have a voice in making the decision.

I hope that helps!
- Michael

**Comment by CristhianMotoche** [comment]
Thanks Michael. I'll join the python-forum.org.

**Comment by metulburr** [comment]
True. Not many people have utilized this. Regardless, i have sent you an invite as a User. This is more or so for group projects of the forum.
